### ISSUE TITLE
getting 404 Not Found

### ISSUE THREAD

**Issue by dinuchiriac** [gustavohenke/grunt-jquery-builder#3]
I'm getting `404: Not Found` in the output file for any versions I try to install. 

My Grunt Config

```
jquery: {
      dist: {
        versions: {
          // Remove everything we don't need
          "3.1.1": [ "ajax/script", "ajax/jsonp", "css", "deprecated", "dimensions", "effects", "event",
            "offset", "wrap", "deferred", "exports/amd", "sizzle" ]
        },
        output: "src/jquery-custom/",
        options: {
          prefix: "jquery-",
          minify: false
        }
      }
    }
```

**Comment by gustavohenke** [comment]
We use the [jquery-builder](https://github.com/jgallen23/jquery-builder) module internally.

jquery-builder itself does download the custom files from their own repository, 
and the project is calling for new maintainers: jgallen23/jquery-builder#22

The latest version available is 2.1.1, and the latest commit is from about 2 years ago.
What you could do at the moment is to contribute the new versions yourself.
